language: scala
scala:
   - 2.12.6
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - botekchristophe@gmail.com
jdk:
  - oraclejdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION test